### ISSUE TITLE
llvm-propeller test program (main.cc, callee.cc) fails after the optimizations.

### ISSUE THREAD

**Issue by uttampawar** [google/llvm-propeller#2]
Hi,
As per the instructions in the RFC, I followed all the steps but final binary built with "propeller-optimize" causes segfault.

The final build also gives warning as,
Final stage build
$ clang++ -O2 main.cc callee.cc -fpropeller-optimize=perf.propeller  -fuse-ld=lld
ld.lld: warning: [Propeller]: Propeller skipped 'a.out'.

$ ./a.out
Segmentation fault (core dumped)

More details in the gist.
https://gist.github.com/uttampawar/88643a0f532160e1de77d76b07d1ad4a
Gist has perf.propeller file, symbol table info before and after the optimizations.

I did see a warning about libtinfo.so.6 during "create_llvm_prof" stage as,

$LLVM_DIR/llvm-propeller/create_llvm_prof --format=propeller --binary=./a.out.labels --profile=perf.data --out=perf.propeller 
/home/upawar/projects/llvm-propeller/create_llvm_prof: /mnt/sdb1/upawar/tools/lib/libtinfo.so.6: no version information available (required by /home/upawar/projects/llvm-propeller/create_llvm_prof)

**Comment by uttampawar** [comment]
@rlavaee Can you help? TIA.

**Comment by rlavaee** [comment]
Thanks for filing the issue. Please make sure the output name is the same between perf.propeller file and the final binary name. Otherwise, the ordering will not take effect (as reported by create_llvm_prof). The segfault happens because of an out_of_bounds access in main.cc (argv[1]).
For sanity check, you may want to reproduce results from plo/sample.c (cd plo ; make sample.propeller.out)

**Comment by uttampawar** [comment]
@rlavaee Thanks for pointing out missing argument error (OOPS!). BTW, there seems to be few dependencies to build "sample.propeller.out" such as BOLT and perf2bolt. Do I need to build these tools?

$ make sample.propeller.out
Failed ....

$ make stage1-compiler # Worked

$ make sample.propeller.out
...
./stage1-compiler -fuse-ld=lld -Wl,-O2 -o sample.out sample_bblabels.o
perf record -o sample.perfdata -e "cycles:u" -j any,u -- ./sample.out
[ perf record: Woken up 100 times to write data ]
[kernel.kallsyms] with build id 37e340b1b5a7cf4f57ba8de2bc777359588a957f not found, continuing without symbols
[ perf record: Captured and wrote 24.980 MB sample.perfdata (32105 samples) ]
make: *** No rule to make target '/mnt/sdb1/upawar/create_llvm_prof_dir/*.cc', needed by '/mnt/sdb1/upawar/create_llvm_prof_dir/create_llvm_prof'.  Stop.

Note: I updated paths.mk for "create_llvm_prof_dir" directory.
Please let me know if any other build environment is missing.

Any help is appreciated. TIA.

**Comment by uttampawar** [comment]
@rlavaee Can you help with this issue please? Am I missing anything? TIA.

**Comment by rlavaee** [comment]
@uttampawar Please resync. I've pushed a fix to break the BOLT dependencies.

**Comment by uttampawar** [comment]
@rlavaee  I'll update the issue with my findings. Thanks.

**Comment by uttampawar** [comment]
This fixes the build issue.
