### ISSUE TITLE
Could you publish a release for llvm-propeller?

### ISSUE THREAD

**Issue by newcfzhao** [google/llvm-propeller#271]
I noticed that propeller hasn't published a release or tag yet.  Do you have any plan for this, please？So we can use a definite version.

**Comment by dhoekwater** [comment]
We're in the final stages of releasing our codebase; once we've finished and added some proper documentation (which should be done by EOY), I'll make a tag.

There are some tentative plans to cut a release with prebuilt binaries at some point, but the timeline is TBD. In the meantime, (nearly) every commit must pass our CI, so you should just be able to build from HEAD (or the most recent commit that passes CI).
