### ISSUE TITLE
Unable to execute command: Abort trap: 6

### ISSUE THREAD

**Issue by binzi56** [google/llvm-propeller#7]
I used xcode11 to run the .dylib generated by llvm-project's clang tools and failed
The following is the error message:

![截屏2020-08-06 下午2 22 49](https://user-images.githubusercontent.com/19421422/89621392-da3eea00-d8c3-11ea-8662-bdaff0488141.png)

---

21 QTPlugin.dylib           0x0000000121da0e30 _GLOBAL__sub_I_CommandLine.cpp + 151300528
22 QTPlugin.dylib           0x0000000121daadfb _GLOBAL__sub_I_CommandLine.cpp + 151341435
23 libdyld.dylib            0x00007fff6e68cd8a dlopen + 171
24 clang                    0x0000000104488ab0 llvm::sys::DynamicLibrary::HandleSet::DLOpen(char const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*) + 32
25 clang                    0x0000000104488e40 llvm::sys::DynamicLibrary::getPermanentLibrary(char const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*) + 48
26 clang                    0x00000001059306ad llvm::sys::DynamicLibrary::LoadLibraryPermanently(char const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*) + 29
27 clang                    0x000000010592f3cd clang::ExecuteCompilerInvocation(clang::CompilerInstance*) + 893
28 clang                    0x00000001008da7f2 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) + 5490
29 clang                    0x000000010090cb96 ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&) + 438
30 clang                    0x00000001054353f8 clang::driver::CC1Command::Execute(llvm::ArrayRef<llvm::Optional<llvm::StringRef> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*, bool*) const::$_1::operator()() const + 40
31 clang                    0x00000001054353c5 void llvm::function_ref<void ()>::callback_fn<clang::driver::CC1Command::Execute(llvm::ArrayRef<llvm::Optional<llvm::StringRef> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*, bool*) const::$_1>(long) + 21
32 clang                    0x000000010447c309 llvm::function_ref<void ()>::operator()() const + 25
33 clang                    0x000000010447c2a3 llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) + 243
34 clang                    0x0000000105433543 clang::driver::CC1Command::Execute(llvm::ArrayRef<llvm::Optional<llvm::StringRef> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*, bool*) const + 499
35 clang                    0x00000001053c6095 clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&) const + 1909
36 clang                    0x00000001053c63b1 clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::__1::pair<int, clang::driver::Command const*> >&) const + 209
37 clang                    0x00000001053f3a55 clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::__1::pair<int, clang::driver::Command const*> >&) + 341
38 clang                    0x000000010090bf2a main + 5258
39 libdyld.dylib            0x00007fff6e6a1cc9 start + 1
clang: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 11.0.0 (/xxxx/llvm-project.git 7392820f989048000562b8fa7dade023dddacb37)
Target: x86_64-apple-darwin19.5.0-simulator
Thread model: posix
InstalledDir: /Users/xxx/llvm-project/build/Debug/bin
clang: error: unable to execute command: Abort trap: 6
clang: note: diagnostic msg: Error generating preprocessed source(s).

**Comment by binzi56** [comment]
The same is true for terminal operations, I don’t know if it’s the plugin or clang version.

**Comment by binzi56** [comment]
CMakeLists.txt is wrong, I solve this problem

**Comment by BlackPeonyFish** [comment]
Dear author, how did you modify the CMakeLists.txt file to solve this problem?
